baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile1

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
#Dropdown menu
# - identifier: dropdown
#   title: Example dropdown menu
#   name: Dropdown
#   weight: 3
# - identifier: dropdown1
#   title: example dropdown 1
#   name: example 1
#   url: /#
#   parent: dropdown
#   weight: 1
# - identifier: dropdown2
#   title: example dropdown 2
#   name: example 2
#   url: /#
#   parent: dropdown
#   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
  # disableThemeToggle: true
  # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    #    brandLogo: "/images/laptop.jpg" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Home" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Bianca."
    subtitle: "Front-end software developer passionate about solving problems"
    content: "I have invested more than 400 hours solving algorithmic problems to develop my programming mindset and have built projects to practice working with programming languages and technologies. I work hard for my dream because I believe that hard work surpasses talent."
    image: /images/profile-image.jpg
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/cv-bianca-seleveschi.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/BiancaSeleveschi?tab=repositories
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/bianca-seleveschi/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/profile2.jpg"
    content: |-

      Passionate about personal growth and making a positive impact, I envision myself as a small but determined entity within the vast ocean of individuals dedicated to improving lives. Although my initial inclination led me toward the field of medicine, I discovered a lingering sense of unfulfillment. It was during this period of introspection that I turned my attention toward my brother, a programmer, and began to explore the fascinating world he was immersed in. Eager to understand the intricacies of programming, I eagerly sought his guidance, posing countless questions and diving deep into the subject matter.
      
      Summoning the courage to step out of my comfort zone, I abandoned my previous job and ventured into the world of programming. Fueling my curiosity, I enrolled in a comprehensive programming course, eager to acquire new knowledge and skills.
      
      Following the programming course, I am more motivated and determined than ever. I stand resolute and fully committed to my journey in front-end programming. Each step I take is driven by my determination to grow, learn, and make a meaningful impact in this ever-evolving field.    

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Vue.js"
        - "Vuex"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Git"
        - "Algorithms"
        - "Data Structures"
        - "jQuery"
        - "Firebase"
        - "Bootstrap"



  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer Trainee"
        company: "Just code IT"
        url: "https://www.justcodeit.ro/"
        date: "2022-2023"
        content: " | Acquired a solid understanding of HTML, CSS, and JavaScript |
Learned to build dynamic and interactive web applications using Vue.js - utilizing components, directives, and state management techniques |
Utilized Git and GitHub for effective version control |
Applied Bootstrap framework to develop responsive and visually appealing web applications |
Leveraged Firebase services to implement real-time data storage, user authentication |
Demonstrated strong problem-solving skills and proficiency in implementing efficient algorithms |
Gained familiarity with database concepts"
      - job: "Dental Assistant"
        company: "Stomestet"
        url: "https://stomestet.ro/"
        date: "Nov 2021 - June 2022"
        content: " | Preparing patients for dental work 
        |  Helping with infection control by sterilizing and disinfecting instruments, setting up instrument trays, preparing materials, and assisting with dental procedures
        |  Assisting dentists in managing medical and dental emergencies when necessary
         | Forming preliminary impressions for study casts and occlusal registrations for mounting study casts
         | Ordering dental supplies and maintaining dental equipment inventory"
      - job: "Dental Assistant"
        company: "Cosem"
        date: "Nov 2016 - April 2018"
        url: "https://www.cosem.fr/"
        content: "  | Preparing patients for dental work
       | Helping with infection control by sterilizing and disinfecting instruments, setting up instrument trays, preparing materials, and assisting with dental procedures
       | Assisting dentists in managing medical and dental emergencies when necessary
       | Assisting dental hygienists with procedures when necessary
      | Providing postoperative instructions as directed by the dentist"


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Front-End Developer Certified"
        school:
          name: "Just code IT"
          url: "https://www.justcodeit.ro/"
        date: "2022 - 2023"
        content: ""
      - title: "Bachelor's degree in Economics"
        school:
          name: "Technical University of Cluj Napoca"
          url: "https://www.utcluj.ro/"
        date: "2018 - 2021"
        content: ""
      - title: "Bachelor's degree, General Nurse"
        school:
          name: "Post Secondary School Henri Coandă"
          url: "https://univ-henricoanda.ro/scoala-postliceala-henri-coanda-baia-mare/"
        date: "2018 - 2021"
        content: ""

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Shopping app
        content: The shopping app I worked on offers a user-friendly interface, convenient authentication and favorites features, as well as an efficient browsing, searching and make online purchases. It aims to provide users with an enjoyable and hassle-free online shopping experience.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://shopping-app-meduzza.netlify.app/
        badges:
          - "VueJs"
          - "Firebase Auth"
          - "Firestore Database"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
      - title: Events app
        content: This events app on is designed to simplify the process of discovering and attending various events. Users can easily search for events based on their interests and location. They can select the event they are interested in attending and securely purchase tickets with just a few clicks.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://eventgo-app.netlify.app/
        badges:
            - "VueJs"
            - "Bootstrap"
            - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter
      - title: Recipe app
        content: The recipe app I worked on is a fantastic tool for culinary enthusiasts and home cooks alike. It allows users to add their own recipes or search recipes by name or category, providing a platform for sharing and discovering a wide range of delicious dishes.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo
          link: https://recipe-app-sele.netlify.app/
        badges:
             - "VueJs"
             - "Bootstrap"
             - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2
      - title: Movie app
        content: This movie app offers a seamless experience for movie enthusiasts. With this app, users can easily search for movies based on their preferences. The app categorizes movies by genre, allowing users to browse through different categories and discover films that align with their interests.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://movies-app11.netlify.app/
        badges:
            - "jQuery"
            - "Bootstrap"
            - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter
      - title: Food diary
        content: With this app, users have the ability to add various food items, categorize them, and input their nutritional information such as calories and price. Additionally, the app offers filtering options based on price and calories.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://food-diary1.netlify.app/
        badges:
            - "HTML"
            - "CSS"
            - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Background Color Picker
        content: The Background Color Picker app I worked on allows users to easily change the background color with just a click.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://background-color-picker1.netlify.app/
        badges:
            - "Vue.js"
            - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: bianca.seleveschi@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/BiancaSeleveschi/BiancaSeleveschi
      linkedin: https://www.linkedin.com/in/bianca-seleveschi/
    # List pages like blogs and posts
    listPages:
      disableFeaturedImage: false
    # Single pages like blog and post
    singlePages:
      readTime:
        enable: true
        content: "min read"
      scrollprogress:
        enable: true
    # For translations
    terms:
      read: "Read"
      toc: "Table Of Contents"
      copyright: "All rights reserved"
      pageNotFound: "Page not found"
      emailText: "Check out this site"
    datesFormat:
      article: "Jan 2, 2006"
      articleList: "Jan 2, 2006"
      articleRecent: "Jan 2, 2006"
